# Generated by Django 3.0.4 on 2020-03-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
