# Generated by Django 3.0.4 on 2020-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_loan_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='reminder',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
