# Generated by Django 3.0.4 on 2020-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200401_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='reminder',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
